version: '3.10'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=your_database_name
      - POSTGRES_USER=your_database_user
      - POSTGRES_PASSWORD=your_database_password
      - POSTGRES_HOST=db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app_network

  # web:
  #   build: .
  #   command: >
  #     sh -c "python manage.py migrate &&
  #            python manage.py collectstatic --noinput &&
  #            gunicorn lunch_decision.wsgi:application --bind 0.0.0.0:8000"
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   networks:
  #     - app_network

  dev:
    # extends: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
      - POSTGRES_DB=your_database_name
      - POSTGRES_USER=your_database_user
      - POSTGRES_PASSWORD=your_database_password
      - POSTGRES_HOST=db
    volumes:
      - ./lunch_decision:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
